version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_REGION=us-west-2
    volumes:
      - ./dynamodb_data:/home/db/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/db/dynamodblocal/data/

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - "5000:5000"
    env_file: ./server/.env
    depends_on:
      - dynamodb
